/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import javax.swing.JFrame;

import java.awt.Color;
import java.security.PublicKey;
import java.security.Security;
import java.util.ArrayList;
//import java.util.Base64;
import java.util.HashMap;
import java.util.Scanner;
import static org.bouncycastle.crypto.tls.CipherType.block;


import org.bouncycastle.jce.provider.BouncyCastleProvider;

/**
 *
 * @author lucth
 */
public class GiaoDienkhach extends javax.swing.JFrame {

    /**
     * Creates new form ManChoi
     */
    public GiaoDienkhach() {
    	Noobchain.NoobCoin.addWallet();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tongiaithuong = new javax.swing.JTextField();
        thoigian = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dangnhap = new javax.swing.JButton();
        dangky = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        chucnang = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        themnguoidung = new javax.swing.JButton();
        dangnhaptk = new javax.swing.JButton();
        xemblock = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 102, 204));
        setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        dangnhap.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        dangnhap.setForeground(new java.awt.Color(255, 51, 51));
        dangnhap.setText("Đăng nhập");
        jPanel2.add(dangnhap);
        dangnhap.setBounds(830, 10, 101, 25);

        dangky.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        dangky.setForeground(new java.awt.Color(255, 0, 51));
        dangky.setText("Đăng Ký");
        jPanel2.add(dangky);
        dangky.setBounds(950, 10, 85, 25);

        jLabel4.setFont(new java.awt.Font("VNI-Murray", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lucky BK");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(280, 10, 130, 35);

        add(jPanel2);
        jPanel2.setBounds(0, 0, 570, 50);
        
        remove(chucnang);
	    chucnang = new datso(Noobchain.SmartContract.time, null);
	    chucnang.setBounds(150, 60, 440, 340);
		chucnang.setBorder(javax.swing.BorderFactory.createLineBorder(Color.black));
		add(chucnang);
		repaint();
		revalidate();
        chucnang.setBounds(170, 60, 380, 360);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        themnguoidung.setBackground(new java.awt.Color(0, 102, 102));
        themnguoidung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        themnguoidung.setForeground(new java.awt.Color(255, 255, 255));
        themnguoidung.setText("Đăng ký");
        jPanel1.add(themnguoidung);
        themnguoidung.setBounds(20, 60, 130, 30);
        themnguoidung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	Application.dangky.dangkychay();
            }
        });

        dangnhaptk.setBackground(new java.awt.Color(0, 102, 102));
        dangnhaptk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dangnhaptk.setForeground(new java.awt.Color(255, 255, 255));
        dangnhaptk.setText("Đăng nhập");
        dangnhaptk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangnhaptkActionPerformed(evt);
            }
        });
        jPanel1.add(dangnhaptk);
        dangnhaptk.setBounds(20, 10, 130, 30);

        xemblock.setBackground(new java.awt.Color(0, 102, 102));
        xemblock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xemblock.setForeground(new java.awt.Color(255, 255, 255));
        xemblock.setText("Xem block");
        jPanel1.add(xemblock);
        xemblock.setBounds(20, 110, 130, 30);
        xemblock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBlock shB = new showBlock();
                shB.setSize(700,450);
                shB.setVisible(true);
                shB.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }
        });
        add(jPanel1);
        jPanel1.setBounds(0, 50, 160, 380);
        
    }// <                     

    private void dangnhaptkActionPerformed(java.awt.event.ActionEvent evt) { 

        Application.dangnhap.dangnhapchay();
    }                                          
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	GiaoDienkhach nv = new GiaoDienkhach();
		nv.setSize(580,473);
		nv.setVisible(true);
    }
    // Variables declaration - do not modify                     
    private javax.swing.JPanel chucnang;
    private javax.swing.JButton dangky;
    private javax.swing.JButton dangnhap;
    private javax.swing.JButton dangnhaptk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton themnguoidung;
    private javax.swing.JLabel thoigian;
    private javax.swing.JTextField tongiaithuong;
    private javax.swing.JButton xemblock;
    // End of variables declaration                   
}
