/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import java.awt.Color;

import Noobchain.Wallet;

/**
 *
 * @author lucth
 */
public class GiaoDienNguoiDung extends javax.swing.JFrame {
	
	public static Wallet user;
    /**
     * Creates new form GiaoDienNguoiDung
     */
    public GiaoDienNguoiDung(Wallet tmp) {
        initComponents();
        this.user = tmp;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chucnang = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        datso = new javax.swing.JButton();
        guitien = new javax.swing.JButton();
        laysodu = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("VNI-Murray", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lucky BK");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(280, 10, 130, 35);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 600, 50);

        chucnang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(chucnang);
        chucnang.setBounds(150, 60, 440, 340);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        datso.setBackground(new java.awt.Color(0, 102, 102));
        datso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        datso.setForeground(new java.awt.Color(255, 255, 255));
        datso.setText("Đặt số may mắn");
        jPanel1.add(datso);
        datso.setBounds(0, 5, 130, 30);
        datso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	remove(chucnang);
			    chucnang = new datso(Noobchain.SmartContract.time, user);
			    chucnang.setBounds(150, 60, 440, 340);
				chucnang.setBorder(javax.swing.BorderFactory.createLineBorder(Color.black));
				add(chucnang);
				repaint();
				revalidate();
            }
        });

        guitien.setBackground(new java.awt.Color(0, 102, 102));
        guitien.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        guitien.setForeground(new java.awt.Color(255, 255, 255));
        guitien.setText("Chuyển tiền");
        guitien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	remove(chucnang);
			    chucnang = new guitien(user);
			    chucnang.setBounds(150, 60, 440, 340);
				chucnang.setBorder(javax.swing.BorderFactory.createLineBorder(Color.black));
				add(chucnang);
				repaint();
				revalidate();
            }
        });
        jPanel1.add(guitien);
        guitien.setBounds(0, 120, 130, 30);

        laysodu.setBackground(new java.awt.Color(0, 102, 102));
        laysodu.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        laysodu.setForeground(new java.awt.Color(255, 255, 255));
        laysodu.setText("Xem số dư");
        jPanel1.add(laysodu);
        laysodu.setBounds(0, 60, 130, 30);
        laysodu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	System.out.println("\nWalletA's balance is: " + user.getBalance());
            	remove(chucnang);
			    chucnang = new sodu(user);
			    chucnang.setBounds(150, 60, 440, 340);
				chucnang.setBorder(javax.swing.BorderFactory.createLineBorder(Color.black));
				add(chucnang);
				repaint();
				revalidate();
                
            }
        });

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 49, 140, 350);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>                        

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                             
        System.exit(0);
    }                                            

    private void guitienActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	GiaoDienNguoiDung nv = new GiaoDienNguoiDung(null);
		nv.setSize(610,473);
		nv.setVisible(true);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JPanel chucnang;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JButton dangky;
    private javax.swing.JButton dangnhap;
    private javax.swing.JButton datso;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton guitien;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton laysodu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration                   

}
