/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import Noobchain.Wallet;

/**
 *
 * @author lucth
 */
public class guitien extends javax.swing.JPanel {
	public static Wallet user;
    /**
     * Creates new form chitietluong
     */
    public guitien(Wallet tmp) {
        this.user = tmp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	jLabel3 = new javax.swing.JLabel();
        xacnhan = new javax.swing.JButton();
        huy = new javax.swing.JButton();
        sotiengui = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        taikhoan = new javax.swing.JTextField();
        guitien = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(440, 340));
        setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tài khoản:");
        add(jLabel3);
        jLabel3.setBounds(100, 130, 130, 17);

        sotiengui.setText("");
        add(sotiengui);
        sotiengui.setBounds(200, 170, 100, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Chuyển tiền");
        add(jLabel1);
        jLabel1.setBounds(170, 60, 130, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Số tiền gửi:");
        add(jLabel4);
        jLabel4.setBounds(100, 170, 80, 17);

        taikhoan.setText("");
        add(taikhoan);
        taikhoan.setBounds(200, 130, 100, 20);

        guitien.setText("Xác nhận");
        guitien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	Noobchain.Block tmp = Noobchain.NoobCoin.blockchain.get( Noobchain.NoobCoin.blockchain.size()-1);
            	Noobchain.Block tmp2 = new Noobchain.Block(tmp.hash);
                tmp2.addTransaction(user.sendFunds(Wallet.getKey(taikhoan.getText()), Float.parseFloat(sotiengui.getText())));
                Noobchain.NoobCoin.addBlock(tmp2);
            }
        });
        add(guitien);
        guitien.setBounds(130, 220, 110, 23);
    }// </editor-fold>                        

    private void xacnhanActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void huyActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   


    // Variables declaration - do not modify                     
    private javax.swing.JButton guitien;
    private javax.swing.JButton huy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField sotiengui;
    private javax.swing.JTextField taikhoan;
    private javax.swing.JButton xacnhan;
    // End of variables declaration                   
}
