/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import javax.swing.JScrollPane;
import javax.swing.JTextArea;

import Noobchain.NoobCoin;

/**
 *
 * @author kaito
 */
public class showBlock extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public showBlock() {
        initComponents();
        	reload();
        
    }
    
    public void reload(){
    	String tmp = NoobCoin.blockchain.toString();
        BlockChain.setText(tmp);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        BlockChain = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        BlockChain.setEditable(false);
        BlockChain.setColumns(20);
        BlockChain.setRows(5);
        jScrollPane2.setViewportView(BlockChain);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(15, 89, 637, 304);

        jLabel1.setFont(new java.awt.Font("Jamrul", 1, 36)); // NOI18N
        jLabel1.setText("Block");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(15, 36, 271, 47);

        pack();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextArea BlockChain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration                   
}
